#include "component.hpp"

WAVERESPAWNTIMEPLAYER = 30;
WAVERESPAWNTIMEBLU = 180;
WAVERESPAWNTIMEOPF = 180;
WAVERESPAWNTIMEIND = 180;

WAVERESPAWNBLU = false;
WAVERESPAWNOPF = false;
WAVERESPAWNIND = false;
WAVERESPAWNTIMELEFTBLU = WAVERESPAWNTIMEBLU;
WAVERESPAWNTIMELEFTOPF = WAVERESPAWNTIMEOPF;
WAVERESPAWNTIMELEFTIND = WAVERESPAWNTIMEIND;
MAXRESPAWNTIME = 1200;
RESPAWNWAVEEXTRATIME = 30;
WAVERESPAWNSTATUSBLU = "";
WAVERESPAWNSTATUSOPF = "";
WAVERESPAWNSTATUSIND = "";

publicVariable "WAVERESPAWNTIMEPLAYER";
publicVariable "WAVERESPAWNTIMEBLU";
publicVariable "WAVERESPAWNTIMEOPF";
publicVariable "WAVERESPAWNTIMEIND";

publicVariable "WAVERESPAWNBLU";
publicVariable "WAVERESPAWNOPF";
publicVariable "WAVERESPAWNIND";
publicVariable "WAVERESPAWNTIMELEFTBLU";
publicVariable "WAVERESPAWNTIMELEFTOPF";
publicVariable "WAVERESPAWNTIMELEFTIND";
publicVariable "MAXRESPAWNTIME";
publicVariable "RESPAWNWAVEEXTRATIME";
publicVariable "WAVERESPAWNSTATUSBLU";
publicVariable "WAVERESPAWNSTATUSOPF";
publicVariable "WAVERESPAWNSTATUSIND";
